version: '3'

services:
  highzer:
    image: ghcr.io/breuerfelix/highzer:latest
    build: .
    environment:
      - UPLOAD_URL=http://localhost:80
      - PASSPHRASE=uploadpy
    volumes:
      - ./data:/usr/app/data
