[tool.poetry]
name = "highzer"
version = "0.1.0"
description = "Twitch Stream Analyzer"
authors = ["Felix Breuer <f.breuer94@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
click = "^7.1.2"
numpy = "^1.19.1"
scipy = "^1.5.2"
python-ffmpeg = "^1.0.11"
google-api-python-client = "^1.10.1"
oauth2client = "^4.1.3"
schedule = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
